schema_version = "1.3"

[task]
name = "toolathlon/yahoo-analysis"
description = "Evaluate the accuracy of historical analyst ratings for NVIDIA (NVDA) and Apple (AAPL) based on subsequent stock price performance over 4, 5, and 6-mo"
keywords = ["toolathlon", "yahoo-finance", "filesystem", "terminal"]

[metadata]
toolathlon_task = "yahoo-analysis"
toolathlon_split = "finalpool"
needed_mcp_servers = ["yahoo-finance", "filesystem", "terminal"]
launch_time = "2026-07-31 16:48:29"

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"
