schema_version = "1.3"

[task]
name = "toolathlon/payable-invoice-checker"
description = "Help me automatically update the two existing tables in the PURCHASE_INVOICE database with all the received receipts in my workspace. For receipts tha"
keywords = ["toolathlon", "emails", "pdf-tools", "filesystem", "snowflake"]

[metadata]
toolathlon_task = "payable-invoice-checker"
toolathlon_split = "finalpool"
needed_mcp_servers = ["emails", "pdf-tools", "filesystem", "snowflake"]

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 1200.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"

[environment.healthcheck]
command = "test -f /var/run/toolathlon/ready"
interval_sec = 5.0
timeout_sec = 10.0
start_period_sec = 5.0
start_interval_sec = 5.0
retries = 120
