schema_version = "1.3"

[task]
name = "toolathlon/dietary-health"
description = "I am a male university student, and my detailed body information is in `body.md`. I plan to create a fitness plan for the next 3 months, and I am curr"
keywords = ["toolathlon", "filesystem", "howtocook", "excel", "terminal"]

[metadata]
toolathlon_task = "dietary-health"
toolathlon_split = "finalpool"
needed_mcp_servers = ["filesystem", "howtocook", "excel", "terminal"]
launch_time = "2026-07-31 16:48:25"

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"
