schema_version = "1.3"

[task]
name = "toolathlon/reimbursement-form-filler"
description = "I'm an accountant in the R&D department of a tech company, and I need your help compiling commuting expense reimbursement forms of all department memb"
keywords = ["toolathlon", "filesystem", "excel", "pdf-tools", "terminal"]

[metadata]
toolathlon_task = "reimbursement-form-filler"
toolathlon_split = "finalpool"
needed_mcp_servers = ["filesystem", "excel", "pdf-tools", "terminal"]
launch_time = "2026-07-31 16:48:27"

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"
