schema_version = "1.3"

[task]
name = "toolathlon/identify-all-songs"
description = "Please help me find the YouTube video titled ' Top hits 2024 playlist Trending music 2024 Best songs 2024 updated weekly (Playlist Hits)' uploaded by "
keywords = ["toolathlon", "filesystem", "youtube-transcript", "playwright_with_chunk", "fetch"]

[metadata]
toolathlon_task = "identify-all-songs"
toolathlon_split = "finalpool"
needed_mcp_servers = ["filesystem", "youtube-transcript", "playwright_with_chunk", "fetch"]

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 1200.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"

[environment.healthcheck]
command = "test -f /var/run/toolathlon/ready"
interval_sec = 5.0
timeout_sec = 10.0
start_period_sec = 5.0
start_interval_sec = 5.0
retries = 120
