schema_version = "1.3"

[task]
name = "toolathlon/arrange-workspace"
description = "Please help me organize the files in my workspace. The file structure should be as shown below. "
keywords = ["toolathlon", "filesystem", "terminal", "pdf-tools", "excel"]

[metadata]
toolathlon_task = "arrange-workspace"
toolathlon_split = "finalpool"
needed_mcp_servers = ["filesystem", "terminal", "pdf-tools", "excel"]
launch_time = "2026-07-31 16:48:21"

artifacts = ["/app"]

[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 600.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 2048
network_mode = "public"
workdir = "/app"
